module.exports = {
  READY: 'READY',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  STOPPED: 'STOPPED',
  // command
  BUYING: 'BUYING',
  BOUGHT: 'BOUGHT',
  SELLING: 'SELLING',
  SOLD: 'SOLD',
  NOT_ENOUGH_MONEY: 'NOT_ENOUGH_MONEY',

  // license
  ACTIVE: 'ACTIVE',
  DISABLE: 'DISABLE',
  EXPRIED: 'EXPRIED'
}
